site_name: Introducing Kafka

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - What is Kafka?: what-is-kafka.md
  - Running Kafka on Local: running-kafka-on-local.md
  - Sending your First Message: sending-your-first-message.md
  - Understanding Consumer Groups: understanding-consumer-groups.md
  - Kafka Partitioning: kafka-partitioning.md
  - Python for Kafka: python-for-kafka.md
  - Python for Kafka with Schema Registry (on Confluent Platform): python-for-kafka-with-schema-registry-on-confluent-platform.md
